### ISSUE TITLE
prebuild install error "Could not detect abi for version 20.1.4 and runtime electron."

### ISSUE THREAD

**Issue by thealexbaron** [thiagoelg/node-printer#59]
Node: 16.16.0 (lts)
OS: Windows 10
@thiagoelg/node-printer: 0.6.2
[electron v20.0.2](https://github.com/electron/electron/releases/tag/v20.0.2)

```
  • install prebuilt binary  name=@thiagoelg/node-printer version=0.6.2 platform=win32 arch=x64 napi=
  • build native dependency from sources  name=@thiagoelg/node-printer
                                          version=0.6.2
                                          platform=win32
                                          arch=x64
                                          napi=
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=C:\Users\Alex\webship-link-3\release\app\node_modules\node-abi\index.js:36
      throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
      ^

    Error: Could not detect abi for version 20.1.4 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (C:\Users\Alex\webship-link-3\release\app\node_modules\node-abi\index.js:36:9)
        at module.exports (C:\Users\Alex\webship-link-3\release\app\node_modules\prebuild-install\rc.js:52:57)   
        at Object.<anonymous> (C:\Users\Alex\webship-link-3\release\app\node_modules\prebuild-install\bin.js:8:25)
        at Module._compile (node:internal/modules/cjs/loader:1105:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
        at node:internal/main/run_main_module:17:47
```

I'm able to build the module and use it in the development flow but when I try to build my app, I'm getting this. Any ideas?

**Comment by joaodematejr** [comment]
+1
