### ISSUE TITLE
printer module error: No Such file or directory at Object.printDirect

### ISSUE THREAD

**Issue by anniecarm** [thiagoelg/node-printer#60]
Annies-MacBook-Pro:pr-printer-main anniecarmichael$ node print.js
{
  question: 'How can we as designers help the lives and the world with innovative products',
  time: '7/22/2022 4:23:53'
}
printer module error: Error: No such file or directory
/Users/anniecarmichael/Desktop/pr-printer-main/node_modules/@thiagoelg/node-printer/lib/printer.js:242
            var res = printer_helper.printDirect(data, printer, docname, type, options);
                                     ^

Error: No such file or directory
    at Object.printDirect (/Users/anniecarmichael/Desktop/pr-printer-main/node_modules/@thiagoelg/node-printer/lib/printer.js:242:38)
    at sendPrint (file:///Users/anniecarmichael/Desktop/pr-printer-main/print.js:63:13)
    at printRandomQuestion (file:///Users/anniecarmichael/Desktop/pr-printer-main/print.js:79:3)
    at file:///Users/anniecarmichael/Desktop/pr-printer-main/print.js:82:1
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
Annies-MacBook-Pro:pr-printer-main anniecarmichael$ 
<img width="915" alt="Screen Shot 2022-10-31 at 5 28 44 PM" src="https://user-images.githubusercontent.com/42788203/199114542-49dc0eca-0f62-4f33-bb29-895a87180d4a.png">

**Comment by anniecarm** [comment]
I have tried many different solutions and added and removed the files again but no matter what I always end up back with this error. The code is finding the text correctly and my computer is able to print to the printer directly, but node print.js is unable to print because of this error.

**Comment by fpelizza** [comment]
Same error
